### ISSUE TITLE
Mvar_lwt.guarded doesn't put back s in case of exception

### ISSUE THREAD

**Issue by JEnoch** [atolab/apero#2]
https://github.com/atolab/apero/blob/80072e98adc47f1ffd94daf6e4ba4c23b740286b/src/core/mvar.ml#L50

Reading this code, I think it should be similar to the one in guarded_and_then, where s is put back in the mvar in case of exception:
`(fun e -> put m s >>= fun () -> Lwt.fail e)`

Am I wrong?

**Comment by kydos** [comment]
That's right. can you please add a put of the original state?
